name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
        compiler: [ gcc, clang ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: install libusb
      run: sudo apt-get -y install libusb-1.0-0-dev
    - name: build
      env:
        CC: ${{ matrix.compiler }}
      run: make
